### ISSUE TITLE
possible drat.builder issues?

### ISSUE THREAD

**Issue by cboettig** [cboettig/drat#2]
Confirm that a package can still fetch after it has been updated.  Looks like `packages_src` is using bare repos?  (e.g. cannot pull a repo when it has changed?)  

Either all packages `fetch` without reporting any pulling of new versions, or they seem to error.  

Getting errors like: 

```
Error in run_system(Sys.which("git"), c("-C", path, "fetch", "origin",  : 
  Running command:
  '/usr/bin/git' -C packages_src/dplyr fetch origin *:*
had status 1
Program output:
--------------------------------------------------------------------------------
From https://github.com/hadley/dplyr
 ! [rejected]        refs/pull/967/merge -> refs/pull/967/merge  (non-fast-forward)
--------------------------------------------------------------------------------
Calls: build ... fetch_package_sources -> fetch_package -> git_fetch_all -> run_system
Execution halted
```

**Comment by cboettig** [comment]
@richfitz have you seen anything like this?  I seem to keep getting this whenever a version has been updated.  (Not a problem on circle since it has to fetch everything from scratch anyhow, but a bit a nuisance locally)

**Comment by richfitz** [comment]
That's weird - no it all works here, and over a few different versions of git.  I set that slightly bizarre system up to try and allow access to all branches on the remote.  Obviously it's not robust!  (I think it does require a fairly recent git).

I'll switch that out for the `clone --mirror` option, though at that point I should probably admit defeat and swap out git2r (https://github.com/richfitz/drat.builder/issues/8).  Otherwise we could just grab zipballs?

**Comment by cboettig** [comment]
issues seem to be gone.
